# This file was generated by GoReleaser. DO NOT EDIT.
cask "ores" do
  name "ores"
  desc "Open Risk Evaluation & Scoring — deterministic cybersecurity risk scoring engine"
  homepage "https://github.com/rigsecurity/ores"
  version "0.1.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ores"

  on_macos do
    on_intel do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_darwin_amd64.tar.gz"
      sha256 "2a02abac5ebd0736d2fca30ef88edbf48146fc8827502df1428f598da1484dba"
    end
    on_arm do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_darwin_arm64.tar.gz"
      sha256 "aafb4e4b68f5910d0da62abec961356ac693dccd70b8bbf2bcadd0a4ade2af43"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_linux_amd64.tar.gz"
      sha256 "da4518fda116755b6a5df848f7bad5f0419bd29238be68dd7996935456780e57"
    end
    on_arm do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_linux_arm64.tar.gz"
      sha256 "177ffe1afe6da718f2b8891f87edbb4f9c7a16308526d8b0ea51faf6bf986645"
    end
  end

  # No zap stanza required
end
