# This file was generated by GoReleaser. DO NOT EDIT.
cask "ores" do
  name "ores"
  desc "Open Risk Evaluation & Scoring — deterministic cybersecurity risk scoring engine"
  homepage "https://github.com/rigsecurity/ores"
  version "0.1.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ores"

  on_macos do
    on_intel do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_darwin_amd64.tar.gz"
      sha256 "53cf2d6c3d87cc9cd6491040a7d982e30421e959912d5f18025657532cd12810"
    end
    on_arm do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_darwin_arm64.tar.gz"
      sha256 "9cec6da59e84739f0ffef6bc241eba4962a9ddbbcf8a1b11d0807179482ae2fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_linux_amd64.tar.gz"
      sha256 "0c5def32e9d6a620f10def24413664be2d901be53efaf1f02d5535200cc22e5d"
    end
    on_arm do
      url "https://github.com/rigsecurity/ores/releases/download/v#{version}/ores_#{version}_linux_arm64.tar.gz"
      sha256 "1a3404286af04f93df5cb043133f1c65fd49455343e3a4ae93cb0a6757a932b7"
    end
  end

  # No zap stanza required
end
